---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create K8s cluster
      import_role:
        name: roles/setup-k8s-cluster-role

    - name: autoscaler    
      import_role:
        name: roles/cluster-autoscaler-role

    - name: metric server        
      import_role:
        name: roles/metric-server-role   

    - name: nginx server        
      import_role:
        name: roles/install-nginx-ingress-controller-role 
        
    - name: Create RDS instance
      import_role:
        name: roles/setup-rds-role 

    - name: Create VPC peering
      import_role:
        name: roles/setup-vpc-peering-role
 