apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-staging
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: shah.ac@northeastern.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
       ingress:
         class: nginx    