apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 labels:
   name: letsencrypt-staging
 name: letsencrypt-staging
spec:
 acme:
   email: shah.ac@northeastern.com
   http01: {}
   privateKeySecretRef:
     name: letsencrypt-staging
   server: https://acme-v02.api.letsencrypt.org/directory