---
- name: Update Helm repositories
  command: helm repo update

# - name: Add nginx-edge chart repo
#   command: helm repo add nginx-edge "https://helm.nginx.com/edge"

- name: Create crds
  command: "kubectl apply -f crds/"

- name: Create namespace
  command: kubectl create namespace monitoring

- name: Create namespace
  command: kubectl create namespace cert-manager

- name: Deploy latest version of ingress-nginx chart inside monitoring namespace with values      
  command: helm upgrade --install app-nginx ingress-nginx  -n monitoring

- name: add repo for cert-manager
  command: helm repo add jetstack https://charts.jetstack.io

- name: apply crds
  command: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml 

- name: install cert-manager
  command: helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager  --version v1.0.4

- name: configure cluster to use Let`s encrypt cert for ingress-controller
  command: kubectl apply -f roles/install-nginx-ingress-controller-role/tasks/letsencrypt-prod.yaml 

- name: configure cluster to use Let`s encrypt cert for ingress-controller
  command: kubectl apply -f roles/install-nginx-ingress-controller-role/tasks/letsencrypt-staging.yaml    

# helm upgrade --install app-nginx ingress-nginx
# helm upgrade --install cert-manager cert-manager --namespace=cert-manager --version v1.0.3 --set ingressShim.defaultIssuerName=letsencrypt-prod --set ingressShim.defaultIssuerKind=ClusterIssuer --set installCRDs=true