---
# vars file for create-rds-role
service: webapp

aws_region: us-east-1

rds_dbname : "webappdb"

rds_instancename: "webapp-db-instance"

rds_instancetype: "db.t3.micro"

rds_username: "root"

rds_password: "pass1234"

rds_subnetgroup: "webapp_DB_Subnet_Group"

rds_securitygroup: "webapp_DB_Security_Group"

webapp: "user-backend-webapp-db"

vpc_name: "webapp_db-{{ aws_region }}-vpc"
vpc_cidr: 10.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}c"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
