# vars file for create-rds-role
service: webapp
aws_region: us-east-1

rds_dbname : "webappdb"

rds_instancename_w : "webapp-db-instance"
rds_instancename_n : "notifier-db-instance"
rds_instancename_p : "poller-db-instance"

rds_subnetgroup: "DB_Subnet_Group"

rds_securitygroup: "DB_Security_Group"

vpc_name: "db-{{ aws_region }}-vpc"
vpc_cidr: 10.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}c"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22