---
# vars file for create-rds-role
service: webapp

aws_region: us-east-1

rds_dbname_w : "webappdb"
rds_dbname_n : "notifierdb"
rds_dbname_p : "pollerdb"

rds_instancename_w : "webapp-db-instance"
rds_instancename_n : "notifier-db-instance"
rds_instancename_p : "poller-db-instance"

rds_instancetype: "db.t3.micro"

rds_username: "root"

rds_password: "pass1234"

rds_subnetgroup: "DB_Subnet_Group"

rds_securitygroup: "DB_Security_Group"

webapp: "user-backend-webapp-db"
poller: "user-backend-poller-db"
notifier: "user-backend-webapp-db"

vpc_name: "db-{{ aws_region }}-vpc"
vpc_cidr: 10.10.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.10.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.10.2.0/24
    az: "{{ aws_region }}a"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
